version: "3.9"

services:
  
  database:
    image: postgres
    container_name: database
    restart: always
    environment:
      - POSTGRES_PASSWORD=${{ secrets.SA_PASSWORD }}
      - POSTGRES_USER=${{ secrets.SA_USERNAME }}
      - POSTGRES_DB=postgres
    networks:
      - bot-network
  
  bot:
    build: .
    container_name: LiterallyContainer
    restart: unless-stopped
    depends_on: 
      - database
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge